### ISSUE TITLE
Update script/documentation to build project

### ISSUE THREAD

**Issue by camueller** [sanlike0911/node-red-contrib-ui-timelines-chart#14]
Currently in `package.json` a `nodes` folder exists in directory `src`. However, none of the scripts in `package.json` transfers this to the `dist` folder.

How should I build/debug/test? There is no documentation about it ...

In order to be able to build the project I moddief the existing scripts - you may a look at chnages to `package.json` and `tsconfig.json` in the following commits to the forked repository:

https://github.com/camueller/node-red-contrib-ui-timelines-chart/commit/5c9c8de7426589a9c422afed7fbd77e9fcd87246
https://github.com/camueller/node-red-contrib-ui-timelines-chart/commit/30c323b7650ca6cf33acd672bc10a5b374b6352f
https://github.com/camueller/node-red-contrib-ui-timelines-chart/commit/89d37132d528b132b60d2c649dc2076eb09534aa

Please update scripts and documentation to help anybody building/testing your project.

**Comment by sanlike0911** [comment]
If you use windows pc, You can debug it immediately.

1. Move to the current directory of the project
2. Execute the command.
    - `npm install`
    - `./build.bat`
    - `npm run start`
3. Access `http://localhost:1880` from your browser.

> Please update scripts and documentation to help anybody building/testing your project.
Will be adding to the documentation in the next update.

**Comment by sanlike0911** [comment]
Take a look at the documentation and scripts in the following commits.

https://github.com/sanlike0911/node-red-contrib-ui-timelines-chart/commit/50822b7d1b201061cac43bec056ac2d20e742382

**Comment by camueller** [comment]
I tried it again but it still does not work! Here is what I did:
```
axel@p51:/tmp$ git clone git@github.com:sanlike0911/node-red-contrib-ui-timelines-chart.git
axel@p51:/tmp/node-red-contrib-ui-timelines-chart$ npm i
axel@p51:/tmp/node-red-contrib-ui-timelines-chart$ npm run build
axel@p51:/tmp/node-red-contrib-ui-timelines-chart$ npm run start
```

It starts Node-RED but Node-RED does not show the `node-red-contrib-ui-timelines-chart` node.

**Comment by sanlike0911** [comment]
I think the node-red-contrib-ui-timelines-chart installation has failed.
With your build log, I can help you.

**Comment by camueller** [comment]
The build did not fail:
```
axel@p51:/tmp/node-red-contrib-ui-timelines-chart$ npm run build

> node-red-contrib-ui-timelines-chart@0.1.5 build
> npm-run-all clean tsc


> node-red-contrib-ui-timelines-chart@0.1.5 clean
> rimraf dist/*


> node-red-contrib-ui-timelines-chart@0.1.5 tsc
> tsc
```

**Comment by sanlike0911** [comment]
I am very sorry. 
It's my mistake.

Fixed the CPX command.
https://github.com/sanlike0911/node-red-contrib-ui-timelines-chart/commit/41044d3b63238ea5f50f41a079b531a722c908c5

**Comment by camueller** [comment]
At first I thought that it is still not working. Then I realized that your changes are only on branch `develop`.
After I switched to that branch and issued the commands from https://github.com/sanlike0911/node-red-contrib-ui-timelines-chart/issues/14#issuecomment-1007896022 the `timelines chart node` showed up in Node-RED.
